### ISSUE TITLE
 This application does not start on some devices

### ISSUE THREAD

**Issue by vfmradio** [silencebeat/OnlineRadio#2]
Good day! This application does not start on some devices! I can not understand what the problem is, while in the emulator everything works! Is it possible that it depends on the processor 64 or 32?

**Comment by silencebeat** [comment]
what device you used?
can you send me the log?

**Comment by vfmradio** [comment]
It was Alcatel Idol3, as well as xiaomi redmi 4x. But it runs on Alcatel Pop C5. I can send the log later.

**Comment by vfmradio** [comment]
07-04 15:50:03.228 1891-1891/silencebeat.onlineradio E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
07-04 15:50:03.228 1891-1891/silencebeat.onlineradio E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-04 15:50:03.228 1891-1891/silencebeat.onlineradio E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
07-04 15:50:03.228 1891-1891/silencebeat.onlineradio E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-04 15:50:03.442 1891-1891/silencebeat.onlineradio E/linker: /data/app/silencebeat.onlineradio-1/lib/arm/libaacdecoder.so: has text relocations
07-04 15:50:03.447 1891-1891/silencebeat.onlineradio E/AndroidRuntime: FATAL EXCEPTION: main
    Process: silencebeat.onlineradio, PID: 1891
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/silencebeat.onlineradio-1/lib/arm/libaacdecoder.so: has text relocations
        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.spoledge.aacdecoder.Decoder.loadLibrary(Decoder.java:187)
        at com.spoledge.aacdecoder.Decoder.create(Decoder.java:221)
        at com.spoledge.aacdecoder.Decoder.create(Decoder.java:198)
        at com.spoledge.aacdecoder.AACPlayer.createDecoder(AACPlayer.java:508)
        at com.spoledge.aacdecoder.MultiPlayer.createDecoder(MultiPlayer.java:91)
        at com.spoledge.aacdecoder.AACPlayer.<init>(AACPlayer.java:130)
        at com.spoledge.aacdecoder.MultiPlayer.<init>(MultiPlayer.java:81)
        at co.mobiwise.library.RadioPlayerService.getPlayer(RadioPlayerService.java:290)
        at co.mobiwise.library.RadioPlayerService.onCreate(RadioPlayerService.java:145)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3232)
        at android.app.ActivityThread.-wrap5(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
